apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: letsencrypt-production-cert
spec:
  secretName: letsencrypt-production-cert-secret
  dnsNames:
  - k8blackwater.ddnsking.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - k8blackwater.ddnsking.com
  issuerRef:
    name: letsencrypt-production-issuer
    kind: Issuer