apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-production-issuer
spec:
  acme:
    # The ACME production api URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: daniel.foehr@sap.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
#    used to store the issuers secret (used for all certs) -> must be != any cert secret name
      name: letsencrypt-production-issuer-secret
    # Enable the HTTP-01 challenge provider
    http01: {}