apiVersion: v1
kind: Service
metadata:
 name: mongo-service
# namespace: mongospace
 labels:
   name: mongo-service
spec:
 ports:
 - port: 27017
   targetPort: 27017
 clusterIP: None
 selector:
   app: mongo-set