
apiVersion: v1
kind: Namespace
metadata:
  name: mongospace
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-serviceaccount
  namespace: mongospace

---

#apiVersion: rbac.authorization.k8s.io/v1beta1
#kind: Role
#metadata:
#  name: mongo-role
#  namespace: mongospace
#rules:
#  - apiGroups:
#      - ""
#    resources:
#      - pods
#      - namespaces
#    verbs:
#      - get
#      - list
#
#---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: mongo-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
    verbs:
    #      needed for the mongo sidecar
      - get
      - list
      - watch
---

#apiVersion: rbac.authorization.k8s.io/v1beta1
#kind: RoleBinding
#metadata:
#  name: mongo-role-binding
#  namespace: ingress-nginx
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: Role
#  name: mongo-role
#subjects:
#  - kind: ServiceAccount
#    name: mongo-serviceaccount
#    namespace: mongospace
#
#---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: mongo-clusterrole-binding
#  namespace: mongospace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mongo-clusterrole
subjects:
  - kind: ServiceAccount
    name: mongo-serviceaccount
    namespace: mongospace
