apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
 name: mongo-set
# namespace: mongospace
spec:
 serviceName: "mongo-service"
 replicas: 3
 template:
   metadata:
     annotations:
       sidecar.istio.io/inject: "false"
     labels:
       app: mongo-set
       environment: test
   spec:
     serviceAccountName: default
#     serviceAccountName: mongo-serviceaccount
     terminationGracePeriodSeconds: 10
     containers:
       - name: mongo
         image: mongo
         command:
           - mongod
           - "--replSet"
           - rs0
#           see https://github.com/cvallance/mongo-k8s-sidecar/issues/68
           - "--bind_ip"
           - 0.0.0.0
           - "--smallfiles"
           - "--noprealloc"
         ports:
           - containerPort: 27017
         volumeMounts:
           - name: mongo-persistent-storage
             mountPath: /data/db
       - name: mongo-sidecar
         image: cvallance/mongo-k8s-sidecar
         env:
           - name: MONGO_SIDECAR_POD_LABELS
#           need to match template labels - sidecar uses to find other mongo pods
             value: "app=mongo-set,environment=test"
 volumeClaimTemplates:
 - metadata:
     namespace: mongospace
     name: mongo-persistent-storage
     annotations:
       volume.beta.kubernetes.io/storage-class: "fast"
   spec:
     accessModes: [ "ReadWriteOnce" ]
     resources:
       requests:
         storage: 2Gi