apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: goanalyzer-deployment
#  namespace: mongospace
spec:
  selector:
    matchLabels:
      app: goanalyzer
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: goanalyzer
    spec:
      containers:
      - name: go
        image: teamplaya/goanalyzer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---

 apiVersion: v1
 kind: Service
 metadata:
#   namespace: mongospace
   name: goanalyzer-service
   labels:
     run: goanalyzer-service
 spec:
   ports:
   - port: 8080
     protocol: TCP
   type: ClusterIP
   selector:
     app: goanalyzer