---
# Source: cert-manager/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm
  namespace: "default"
  labels:
    app: cert-manager
    chart: cert-manager-v0.5.0
    heritage: Tiller